### ISSUE TITLE
Problema de permisos al crear iniciativa

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/decidim-initiatives#1]
El botón de crear iniciativa aparece **sin estar logueado**. Pero entrando como tedicprueba la opción **no aparece**. 

Sin loguear: 
![seleccion_573](https://user-images.githubusercontent.com/463429/41316150-95685842-6e5f-11e8-9c67-83f099cac645.png)

Logueado:
![seleccion_572](https://user-images.githubusercontent.com/463429/41316182-b2094470-6e5f-11e8-8d55-bab374e59afc.png)

**Comment by diegocrzt** [comment]
Es normal que el botón aparezca cuando no hay ningún usuario loggeado, al parecer es algo que la gente de decidim deciidió hacer así por que en la mayoría de las vistas ese es el comportamiento normal.

La cuenta **tedicprueba** fue creada antes de desarrollarse la autorización automática, entonces está guardada así en la base de datos.

Como estar autorizado es un pre requisito para crear una iniciativa, no se muestra el botón al iniciar sesión con esa cuenta.

En el entorno final de producción esto no va a ocurrir por que todas las cuentas ya van a estar autorizadas automáticamente al confirmarse via e-mail.

Pero como workaround en el peor de los casos se puede disparar la autorización manualmente a traves de del apartado de **Autorizaciones** en el Menú **Mi Cuenta**

![20180614184755_m4800](https://user-images.githubusercontent.com/6553005/41442076-7cf3b23e-7003-11e8-8244-f21929159a9d.png)

Elegir el mecanismo de **Autorización automática**

![20180614184837_m4800](https://user-images.githubusercontent.com/6553005/41442107-a4f11c0e-7003-11e8-8305-1267d1cdbd75.png)

y luego click en **Enviar** 

![20180614184907_m4800](https://user-images.githubusercontent.com/6553005/41442140-b9ca311a-7003-11e8-891c-88f26450d88c.png)

Con esto ya queda la cuenta autorizada

**Comment by lupa18** [comment]
borré el usuario desde su propio perfil y volví a crearlo
