### ISSUE TITLE
Las iniciativas no se están firmando

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/decidim-initiatives#12]
Creé esta iniciativa: https://beta.encarnacion.org.py/initiatives/i-18/committee_requests/new
y ya firmamos dos personas pero sin embargo sigue sin contarlas según aparece en el backend: 

![seleccion_586](https://user-images.githubusercontent.com/463429/42110949-3c20f214-7bb9-11e8-8928-5a42d3be7bdc.png)

Relacionada con https://github.com/TEDICpy/miciudad2/issues/6

**Comment by diegocrzt** [comment]
Esa iniciativa está en etapa de creación, todavía requiere 
## 1- Se conforme el comité (que implica)
### 1.1- El creador de la iniciativa enviar(copiar) el link de invitaciones a los posibles miembros del comité de promoción.
![20180714072814_m4800](https://user-images.githubusercontent.com/6553005/42724311-d679fde4-873d-11e8-892e-1d9b9f3ed86e.png)
### 1.2- Que estos miembros acepten la invitación para formar parte del comité de promoción.
![20180714072931_m4800](https://user-images.githubusercontent.com/6553005/42724314-e29c7eda-873d-11e8-9195-44a93bac4a5c.png)
![20180714072940_m4800](https://user-images.githubusercontent.com/6553005/42724318-eb8f684a-873d-11e8-89be-b96118cbbb11.png)
### 1.3- El creador tiene que aprobar a los miembos del comité (_por lo menos dos usuarios aprobados_)
![20180714074445_m4800](https://user-images.githubusercontent.com/6553005/42724322-f48fb486-873d-11e8-8152-5c04a7a16de4.png)
![20180714074636_m4800](https://user-images.githubusercontent.com/6553005/42724333-350cd566-873e-11e8-9612-238e3f1c1f51.png)

Durante este proceso no se cuentan aún los soportes o votos, los miembros del comité y las aprobaciones **NO** son votos(_soportes/firmas_) Por lo que el contador de soportes sigue siendo 0

![20180714075036_m4800](https://user-images.githubusercontent.com/6553005/42724378-f3e69fda-873e-11e8-9dd7-c54728c462c1.png)


## 2- Que el creador envía la iniciativa a validación técnica. (_Los administradores son notificados vía e-mail_)
![20180714074623_m4800](https://user-images.githubusercontent.com/6553005/42724331-281784a0-873e-11e8-9dde-6882afa24d13.png).
Una vez hecho esto, el creador no puede modificar la iniciativa y solo el administrador controla el flujo
![20180714074803_m4800](https://user-images.githubusercontent.com/6553005/42724340-4ce278a8-873e-11e8-9d39-ea96cece771c.png)

## 3. El administrador revisa y configura la propuesta que está ahora en validación técnica
![20180714075036_m4800](https://user-images.githubusercontent.com/6553005/42724346-5f32f762-873e-11e8-87d9-e1381fecd9d8.png)
![20180714075054_m4800](https://user-images.githubusercontent.com/6553005/42724348-62d6fd96-873e-11e8-9e6b-73fecf2a5c15.png)
Puede agregarle tantas características como quiera
![20180714080135_m4800](https://user-images.githubusercontent.com/6553005/42724349-66261a86-873e-11e8-99f5-3e3e8f82312d.png)
### 4. El administrador publica(_o descarta_) la iniciativa.
![20180714080224_m4800](https://user-images.githubusercontent.com/6553005/42724353-7e9132a4-873e-11e8-956f-9368a83a7e75.png)
Durante este proceso todavía no se pueden contar el número de soportes(firmas, o votos, son lo mismo en decidim.)
![20180714080307_m4800](https://user-images.githubusercontent.com/6553005/42724354-82726794-873e-11e8-9a89-44d86dd12620.png)
### 5. Una vez publicada la iniciativa estará disponible en la plataforma para que todos los usuarios interactuen.
![20180714080425_m4800](https://user-images.githubusercontent.com/6553005/42724361-a97e6770-873e-11e8-968c-167939ed760e.png)
![20180714080449_m4800](https://user-images.githubusercontent.com/6553005/42724362-aa991aa6-873e-11e8-8045-209565eec26c.png)

En este momento si se cuentan los votos 
![20180714080544_m4800](https://user-images.githubusercontent.com/6553005/42724366-b6d6d6e6-873e-11e8-82e3-069616248d6b.png)
![20180714080553_m4800](https://user-images.githubusercontent.com/6553005/42724367-b98a391e-873e-11e8-84cc-4a171f344fe4.png)

![20180714080646_m4800](https://user-images.githubusercontent.com/6553005/42724368-bfaa40b4-873e-11e8-931f-be2056ebca69.png)
![20180714080733_m4800](https://user-images.githubusercontent.com/6553005/42724371-c315320e-873e-11e8-8772-e1d719a906f6.png)

**Comment by lupa18** [comment]
En el paso 1.2 los miembros reciben el enlace, hacen clic y reciben un mensaje algo así como "Enviado para aprobación" y el ciclo se corta allí. Ya probamos con 3 usuarios y varias iniciativas.

**Comment by lupa18** [comment]
ok, entonces estamos fallando en 1.3 pero lo que ocurre es que no se recibe notificación sobre estas solicitudes de "aprobación"

**Comment by lupa18** [comment]
Por otro lado el usuario tedicprueba2 creó la iniciativa https://beta.encarnacion.org.py/admin/initiatives/i-18/edit indica que ya tiene 4 miembros: 

![seleccion_605](https://user-images.githubusercontent.com/463429/42726430-5dad4572-8762-11e8-9682-cc875273dbc4.png)

Pero no se ve cómo aprobarlos (o quizás ya fueron aprobados). 

Pero en la pantalla del listado sigue diciendo 0/3: 

![seleccion_604](https://user-images.githubusercontent.com/463429/42726439-759aac88-8762-11e8-8a8c-3a48b3cdae95.png)

Y tampoco aparece en los listados de iniciativas ni en la portada: 

- https://beta.encarnacion.org.py/initiatives
- https://beta.encarnacion.org.py/initiatives?utf8=%E2%9C%93&filter%5Bsearch_text%5D=&filter%5Bstate%5D=&filter%5Bstate%5D=closed&filter%5Bauthor%5D=&filter%5Bauthor%5D=any&filter%5Btype%5D%5B%5D=&order=random

Falta enviar a validación técnica? cómo se hace? dónde me avisa? cómo me notifica?

**Comment by diegocrzt** [comment]
1 - Si ya fueron todos aprobados por que ya no tienen el check para ser aprobados (yo solo aprobé a Diego Ramírez, así que alguien más aprobó a los otros usuarios, si no fue el creador fue algún otro administrador, decidim no permite auditar esto hoy día y no creo que lo permita en mucho tiempo) 
2 -  La pantalla de soportes sigue diciendo 0/3 por que la iniciativa no está publicada está en estado  **Creada**. Ese conteo de soportes(votos o firmas son lo mismo en decidim) no cuenta los miembros del comité solo los votos(firmas) y solo se puede votar una vez publicada la inciativa
![20180715194041_m4800](https://user-images.githubusercontent.com/6553005/42739534-02a50772-8867-11e8-952e-5bd282ecfee4.png)
3 - No van a aparecer aun en el listado de inciativas hasta estar publicadas, un esquema de estos estados fue explicado anteriormente https://github.com/TEDICpy/decidim-initiatives/issues/3
4 - Efectivamente falta enviar a validación técnica, no existe un mecanismo de notificación para el creador de que ya puede enviar su iniciativa a Validación técnica. El usuario debe ingresar al listado de tanto en tanto y mirar o le tienen que avisar las personas a las que él les compartió el link del comité. No se por que decidim implemento esto así. Pero al ingresar al dashboard administrativo y ver mis iniciativas, el creador puede enviar a validación técnica con el botón gris del formulario (que solo estará disponible una vez se conforme (y apruebe el comité).
![20180715193845_m4800](https://user-images.githubusercontent.com/6553005/42739580-a742fb40-8867-11e8-8869-cf12c2b33061.png)

Una vez hecho el administrador puede completar el proceso, como se describió más arriba.

**Comment by lupa18** [comment]
Al parecer las firmas entran a correr luego de creado el comité por eso la confusión. Cierro por ahora.
