### ISSUE TITLE
Obtener enlace de iniciativa para votar

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/decidim-initiatives#2]
Los enlaces de compartir para votar **solo se muestran una vez**. Según entiendo, son diferentes a los de compartir simplemente. Un ejemplo: 

- Enlace para compartir la iniciativa: https://beta.encarnacion.org.py/initiatives/i-13/ (no está disponible hasta conseguir las 3 firmas)
- Enlace para ser parte del comité: https://beta.encarnacion.org.py/initiatives/i-13/committee_requests/new

No encuentro donde volver a encontrar ese segundo enlace: quizás sea que no busqué bien.

**Comment by diegocrzt** [comment]
Cuando se abre una Iniciativa

![20180614183241_m4800](https://user-images.githubusercontent.com/6553005/41441649-87bfdc9e-7001-11e8-87a3-73473df30ea6.png)

En el widget de la derecha en la pantalla, tiene la opción **Compartir**

![20180614183320_m4800](https://user-images.githubusercontent.com/6553005/41441674-a33930c4-7001-11e8-89fc-eb8484966d99.png)

Que permite compartir en redes sociales o vía un enlace URL

![20180614183329_m4800](https://user-images.githubusercontent.com/6553005/41441708-cbf28876-7001-11e8-93d9-ee6a49887f99.png)

![20180614183348_m4800](https://user-images.githubusercontent.com/6553005/41441712-cf02ef74-7001-11e8-80a7-a26f75c007e8.png)

**Comment by diegocrzt** [comment]
Para el segundo enlance ir a la interfaz administrativa 

![20180702211440_nforce680i](https://user-images.githubusercontent.com/6553005/42194110-5a160e88-7e40-11e8-98d6-b5fd5676e2e2.png)

**Comment by lupa18** [comment]
Bien, ¿pero como usuario? Sino anoté el enlace no voy a volver acceder a él. 

Es importante saber si eso es así pues deberíamos aclararlo en algún lugar.

**Comment by lupa18** [comment]
El segundo enlace se obtiene en la interfaz administrativa del usuario común también.
