### ISSUE TITLE
Eliminar o rechazar iniciativas

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/decidim-initiatives#3]
Veo que existen unas 13 iniciativas: 

![seleccion_574](https://user-images.githubusercontent.com/463429/41317879-849410a6-6e64-11e8-9ccd-09b246a5ae05.png)

Estoy logueado como admin pero no veo las opciones de rechazar o eliminar.

**Comment by diegocrzt** [comment]
Respecto a esto tuve que revisar a fondo el código pro que no hay documentación ni la UI es muy intuitiva al respecto, hasta donde llegué a entender el ciclo de vidad de la iniciativa se puede resumir en el siguiente diagrama de estados 

![initiatives_states](https://user-images.githubusercontent.com/6553005/41492966-c4850f6c-70d0-11e8-8f50-524c03fbf221.png)

Como se puede ver no hay una manera de Eliminar la iniciativa creada, lo que se puede hacer es Descartarla durante el proceso de validación técnica, o se rechaza automáticamente cuando expira su fecha de recolección de firmas y no ha conseguido los suficientes votos. Pero las iniciativas en estado Created (creadas) no se pueden eliminar de la base de datos via UI.

**Comment by lupa18** [comment]
La fecha de recolección está explícita el algún lado?

**Comment by diegocrzt** [comment]
No, este valor no es explicíto, cuando se pulbica la iniciativa, la fecha de inicio de recogida de firmas se establece en hoy/ahora, y se le suma 120 días para la fecha de finalización.

El valor está en duro en el código. No se por qué no externalizó la gente de decidim.

https://github.com/TEDICpy/decidim-initiatives/blob/377b2516a031acefec67e978ebfb9ec507cbfdaa/lib/decidim/initiatives.rb#L41

**Comment by lupa18** [comment]
Allí modifiqué el texto de crear iniciativa y también lo agregaré en preguntas frecuentes.
