### ISSUE TITLE
Agregar aviso de tamaño de imagen al crear iniciativa

### ISSUE THREAD

**Issue by angardi** [TEDICpy/decidim-initiatives#4]
#### Reporte de Bug

* What went wrong?
Al crear una iniciativa, en el paso "Crea", se completan todos los campos y luego se hace click en el boton "siguiente". La pagina se queda cargando por un tiempo bastante largo y luego sale el mensaje "Ha habido un problema con nuestro servidor. Por favor, vuelve a intentarlo más tarde."

* What did you expect should have happened?
Deberia pasar al siguiente paso para la creacion de iniciativa

* What stacktrace or error message from your provider did you see?
"Ha habido un problema con nuestro servidor. Por favor, vuelve a intentarlo mas tarde."

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***: beta.encarnacion.org.py
* ***Browser & version***: Firefox 60

**Comment by angardi** [comment]
El error se produce cuando se adjunta una imagen relativamente grande. La imagen que trate de adjuntar es un JPG de 2.8MB. Cuando adjunto una imagen mas pequeña no hay problema.
En caso de que sea una limitación propia de la plataforma, debería aparecer algún mensaje diciendo que la imagen es muy grande o algo similar

**Comment by diegocrzt** [comment]
Resuelto en #6

**Comment by diegocrzt** [comment]
![20180614181751_m4800](https://user-images.githubusercontent.com/6553005/41441158-6834910a-6fff-11e8-89b7-613b70c50bcb.png)

**Comment by angardi** [comment]
No se podria poner un help text indicando la restricción de forma a que uno ya sepa sobre eso antes de cargar, porque cuando uno carga un archivo, el mismo igual se envia y tarda bastante tiempo en actualizar la pagina, lo que hace parece que la misma esta colgada.

Tambien creo que seria ideal aumentar el limite por lo menos a 4MB, teniendo en cuenta que hoy en dia la mayoria de las fotos tomadas con celulares superan los 2MB y poca gente sabe como reducir el tamaño. En todo caso, si se quiere mantener el temaño, se podría reducir el peso de la imagen desde el backend.

**Comment by lupa18** [comment]
Agregar texto para que el usuario sepa la restricción.

**Comment by lupa18** [comment]
Ya está
