### ISSUE TITLE
Ubicacion de encuentros

### ISSUE THREAD

**Issue by angardi** [TEDICpy/decidim-initiatives#5]
No se visualiza el mapa de los encuentros en el frontend. Tambien seria ideal cambiar el motor de mapas por google maps en vez de open street maps

[https://beta.encarnacion.org.py/initiatives/i-15/f/49/meetings/3](https://beta.encarnacion.org.py/initiatives/i-15/f/49/meetings/3)

**Comment by diegocrzt** [comment]
Corregido en miciudad2 , configuración superpuesta

**Comment by lupa18** [comment]
Esto sigue sin verse en el enlace. 

A @angardi comentarle que OSM es un requerimiento, ¿cuál sería el argumento de usar los mapas privados de google?

**Comment by diegocrzt** [comment]
Este es un problema con la cartografía de paraguay y el servicio que convierte direcciones en coordenadas, está muy incompleto y no es georeferenciable la mayor parte del país, ya habíamos comentado que para el caso de encuentros no podíamos tocar este servicio por que usa un api de here maps y es intrínseco a decidim, ademas de que no tendríamos como reemplazarlo e incluso si pudieramos el problema de la cartografía incompleta de Paraguay nos resultaría en el mismo error, que no se puede generar una miniatura del mapa para una dirección de la cuál no se pueden obtener coordenadas (ej: Municipalidad de Encarnacion, Encarnacion - Paraguay
encarnacion, municipalidad). 

Para otros casos donde las direcciones si pueden ser georeferencias (long/lat) la miniatura se genera correctamente. para la misma iniciativa puede verse el listado de encuentros 
https://beta.encarnacion.org.py/admin/initiatives/i-15/features/49/manage/meetings

Y para otra dirección algo más específico una miniatura es correctamente generada

![20180715195410_m4800](https://user-images.githubusercontent.com/6553005/42739640-e4ad0a1a-8868-11e8-8ec6-da615f29fb4d.png)
